### ISSUE TITLE
"Backpack does not exist" after restoring backup

### ISSUE THREAD

**Issue by Earl-Brown** [trentech/BetterBackpacks#1]
To test the 1.8 spigot build, I created a .zip file of my entire MC server folder structure.  I ran my tests and then restored the backup (deleted the folder and unzipped the archive).

All of the backpacks I had created before I made the .zip file now say "backpack does not exist" when I attempt to use them.  

I can create and use new backpacks, and the old backpacks *are* recognized *as* backpacks - just that they are backpacks that "don't exist".

I can send you the .zip file, if you'd like - some of the backpacks are stored in a chest, so they would be available to other users.

I have reviewed the logs and cannot find anything about missing backpacks...but I can send you those, as well, if you'd like.

**Comment by trentech** [comment]
No Response
